[package]
name = "rk2"
version = "0.1.0"
authors = ["Simon Heath <simon@noctis-productions.com>"]
license = "..."
readme = "README.md"

[dependencies]

ggez = "0.4.0-rc.1"
ggez-goodies = { git = "https://github.com/ggez/ggez-goodies", branch = "master" }
#ggez-goodies = { path = "/home/icefox/src/ggez-goodies" }

lazy_static = "0.2"
slog = "2.0"
slog-term = "2.0"
slog-async = "2.0"
failure = "0.1"
specs = "0.10"
specs-derive = "0.1"
#warmy = "0.3"
warmy = { git = "https://github.com/icefoxen/warmy", branch = "load-with-context" }